version: '3.8'

services:
  backend:
    build: ./fullstack-test-starter-main
    container_name: php_backend
    ports:
      - "8080:80"
    volumes:
      - ./fullstack-test-starter-main:/var/www/html
    depends_on:
      - database

  frontend:
    build: ./client
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
